[package]
name = "integration_test"
version = "0.1.0"
authors = ["Groestlcoin Developers <groestlcoin@gmail.com>"]
edition = "2018"

[dependencies]
groestlcoincore-rpc = { path = "../client" }
groestlcoin = { version = "0.30.0", features = ["serde", "rand"]}
lazy_static = "1.4.0"
log = "0.4"
